function TC008()
{
  TestedApps.GUI.Run();
  let gui = Aliases.GUI;
  let formLogin = gui.FormLogin;
  formLogin.textBoxUsername.SetText("a");
  let textBox = formLogin.textBoxPassword;
  textBox.Click(156, 18);
  textBox.SetText(Project.Variables.Password1);
  formLogin.buttonDangNhap.ClickButton();
  gui.XtraFormMainThuThu.simpleButtonMuonSach.ClickButton();
  let xtraFormMuonSach = gui.XtraFormMuonSach;
  let simpleButton = xtraFormMuonSach.simpleButtonThemMuonSach;
  aqObject.CheckProperty(simpleButton, "Enabled", cmpEqual, true);
  let simpleButton2 = xtraFormMuonSach.simpleButtonXacNhanMuon;
  aqObject.CheckProperty(simpleButton2, "Enabled", cmpEqual, true);
  xtraFormMuonSach.dataGridViewDSSach.ClickCell(3, "ID");
  aqObject.CheckProperty(Aliases.GUI.XtraFormMuonSach.dataGridViewDSSach, "wValue(3, 0)", cmpEqual, 4);
  aqObject.CheckProperty(Aliases.GUI.XtraFormMuonSach.dataGridViewDSSach, "wValue(3, 1)", cmpEqual, "Cuộc sống rất giống cuộc đời");
  simpleButton.ClickButton();
  aqObject.CheckProperty(Aliases.GUI.XtraFormMuonSach.dataGridViewDSSachChon, "wValue(0, 1)", cmpEqual, "4");
  let dataGridView = xtraFormMuonSach.dataGridViewDSSachChon;
  dataGridView.ClickCell(0, "TENSACH");
  let panel = dataGridView.Panel;
  aqObject.CheckProperty(panel.DataGridViewTextBoxEditingControl, "wText", cmpEqual, "Cuộc sống rất giống cuộc đời");
  aqObject.CheckProperty(panel, "Enabled", cmpEqual, true);
  simpleButton2.ClickButton();
  let dlg = gui.dlg;
  aqObject.CheckProperty(dlg.Static3, "WndCaption", cmpEqual, "Trường nhập không được để trống.");
  dlg.btnOK.ClickButton();
  aqObject.CheckProperty(xtraFormMuonSach.textBoxTenDocGiaMuon, "wText", cmpEqual, "");
  let xtraFormMainThuThu = gui.XtraFormMainThuThu;
  gui.XtraFormMuonSach.pictureBox1.Click(35, 21);
  xtraFormMainThuThu.Close();
  formLogin.Close();
}
function TC009()
{
  TestedApps.GUI.Run();
  let gui = Aliases.GUI;
  let formLogin = gui.FormLogin;
  formLogin.textBoxUsername.SetText("a");
  let textBox = formLogin.textBoxPassword;
  textBox.Click(178, 12);
  textBox.SetText(Project.Variables.Password1);
  formLogin.buttonDangNhap.ClickButton();
  gui.XtraFormMainThuThu.simpleButtonMuonSach.ClickButton();
  let xtraFormMuonSach = gui.XtraFormMuonSach;
  let simpleButton = xtraFormMuonSach.simpleButtonKiemTraDocGia;
  aqObject.CheckProperty(simpleButton, "Enabled", cmpEqual, true);
  aqObject.CheckProperty(xtraFormMuonSach.simpleButtonThemMuonSach, "Enabled", cmpEqual, true);
  let simpleButton2 = xtraFormMuonSach.simpleButtonXacNhanMuon;
  aqObject.CheckProperty(simpleButton2, "Enabled", cmpEqual, true);
  textBox = xtraFormMuonSach.textBoxTenDocGiaMuon;
  textBox.Click(122, 9);
  textBox.SetText("Lê Hoàng Công");
  aqObject.CheckProperty(textBox, "wText", cmpEqual, "Lê Hoàng Công");
  simpleButton.ClickButton();
  aqObject.CheckProperty(xtraFormMuonSach.textBoxMaDocGiaMuon, "wText", cmpEqual, "2005");
  simpleButton2.ClickButton();
  let dlg = gui.dlg;
  aqObject.CheckProperty(dlg.Static6, "WndCaption", cmpEqual, "Chưa có sách.");
  dlg.btnOK.ClickButton();
  aqObject.CheckProperty(xtraFormMuonSach.dataGridViewDSSachChon, "Enabled", cmpEqual, true);
  let xtraFormMainThuThu = gui.XtraFormMainThuThu;
  gui.XtraFormMuonSach.pictureBox1.Click(35, 21);
  xtraFormMainThuThu.Close();
  formLogin.Close();
}
function TC010()
{
  TestedApps.GUI.Run();
  let gui = Aliases.GUI;
  let formLogin = gui.FormLogin;
  formLogin.textBoxUsername.SetText("a");
  let textBox = formLogin.textBoxPassword;
  textBox.Click(265, 10);
  textBox.SetText(Project.Variables.Password1);
  formLogin.buttonDangNhap.ClickButton();
  gui.XtraFormMainThuThu.simpleButtonMuonSach.ClickButton();
  let xtraFormMuonSach = gui.XtraFormMuonSach;
  let simpleButton = xtraFormMuonSach.simpleButtonKiemTraDocGia;
  aqObject.CheckProperty(simpleButton, "Enabled", cmpEqual, true);
  let simpleButton2 = xtraFormMuonSach.simpleButtonThemMuonSach;
  aqObject.CheckProperty(simpleButton2, "Enabled", cmpEqual, true);
  let simpleButton3 = xtraFormMuonSach.simpleButtonXacNhanMuon;
  aqObject.CheckProperty(simpleButton3, "Enabled", cmpEqual, true);
  textBox = xtraFormMuonSach.textBoxTenDocGiaMuon;
  textBox.Click(55, 10);
  textBox.SetText("Lê Hoàng Công");
  simpleButton.ClickButton();
  aqObject.CheckProperty(textBox, "wText", cmpEqual, "Lê Hoàng Công");
  aqObject.CheckProperty(xtraFormMuonSach.textBoxMaDocGiaMuon, "wText", cmpEqual, "2005");
  let dataGridView = xtraFormMuonSach.dataGridViewDSSach;
  dataGridView.ClickCell(1, "ID");
  aqObject.CheckProperty(dataGridView, "Enabled", cmpEqual, true);
  aqObject.CheckProperty(Aliases.GUI.XtraFormMuonSach.dataGridViewDSSach, "wValue(1, 0)", cmpEqual, 2);
  aqObject.CheckProperty(Aliases.GUI.XtraFormMuonSach.dataGridViewDSSach, "wValue(1, 1)", cmpEqual, "Đại Việt sử ký toàn thư");
  simpleButton2.ClickButton();
  dataGridView = xtraFormMuonSach.dataGridViewDSSachChon;
  aqObject.CheckProperty(dataGridView, "Enabled", cmpEqual, true);
  aqObject.CheckProperty(Aliases.GUI.XtraFormMuonSach.dataGridViewDSSachChon, "wValue(0, 1)", cmpEqual, "2");
  dataGridView.ClickCell(0, "TENSACH");
  aqObject.CheckProperty(dataGridView.Panel.DataGridViewTextBoxEditingControl, "wText", cmpEqual, "Đại Việt sử ký toàn thư");
  simpleButton3.ClickButton();
  let winword = Aliases.WINWORD;
  let netUIHWND = winword.formPhieumuonDocChiOCChTNgThiChW.panelMsodocktop.toolbar.Ribbon.NUIPane.NetUIHWND;
  netUIHWND.Click(1117, 172);
  netUIHWND.Click(1663, 180);
  OCR.Recognize(winword.wndNUIDialog.NetUIHWND).BlockByText("Không", spLeftMost).Click();
  let dlg = gui.dlg;
  aqObject.CheckProperty(dlg.Static7, "WndCaption", cmpEqual, "Đã mượn sách.");
  dlg.btnOK.ClickButton();
  let xtraFormMainThuThu = gui.XtraFormMainThuThu;
  gui.XtraFormMuonSach.pictureBox1.Click(35, 21);
  xtraFormMainThuThu.Close();
  formLogin.Close();
}